namespace GSharp.TypeChecker;

/// <summary>
/// Represents an equality constraint between two types: Left must equal Right.
///
/// Constraints are generated by the TypeInferrer while walking the AST.
/// For example, `a + b` generates the constraint: type(a) = type(b).
/// All accumulated constraints are then solved together by the Unifier.
///
/// <see cref="Line"/>/<see cref="Column"/> carry the 1-based source position of the
/// expression that produced the constraint (0 when unknown). The Unifier reports them in
/// type-mismatch errors so the language server can place the diagnostic on the right line
/// instead of falling back to line 1.
/// </summary>
public record TypeConstraint(GsType Left, GsType Right, int Line = 0, int Column = 0);
