namespace GSharp.TypeChecker;

/// <summary>
/// Represents an equality constraint between two types: Left must equal Right.
///
/// Constraints are generated by the TypeInferrer while walking the AST.
/// For example, `a + b` generates the constraint: type(a) = type(b).
/// All accumulated constraints are then solved together by the Unifier.
/// </summary>
public record TypeConstraint(GsType Left, GsType Right);
